### ISSUE TITLE
degree_days

### ISSUE THREAD

**Issue by pvhpsb** [Ernst79/degree-days#34]
is degree-days still available in HACS?

**Comment by pvhpsb** [comment]
Thanks

**Comment by pvhpsb** [comment]
Can anyone help me with a "helper" to enter the correct gas value?
I use the "DSMR reader"

**Comment by nelbs** [comment]
You have to create a [utility meter](https://www.home-assistant.io/integrations/utility_meter/) with 
sensor.dsmr_reading_extra_device_delivered as the input sensor

**Comment by pvhpsb** [comment]
Sory i dont have a "sensor.dsmr_reading_extra_device_delivered" sensor

**Comment by nelbs** [comment]
Maybe your dsmr reader sensor have different names but there should be a sensor which reports the gas usage.

**Comment by pvhpsb** [comment]
Ok i found  "sensor.dsmr_reader_gas_delivered" what else must i given  cycles? offset?
Mij year is from 29 april 24 to 28 april 25
Thank you in advance

**Comment by nelbs** [comment]
All possible input for the [utility meter](https://www.home-assistant.io/integrations/utility_meter/) integration is well-documented on the Home Assistant website. You don't need to enter cycles and offset since the gas sensor only provides increasing values and is never reset. To make a good forecast, the utility meter must be to 0 on 29 april. Since this date is in the past, you will need to calibrate the utility meter once with `utility_meter.calibrate`. You need to calculate the gas usage from 29-4 till now and set the utility meter to that value.
Every 28-4 in the future, you will need to reset the utility meter to 0 with the action `utility_meter.reset` (for example, with an automation).

**Comment by nelbs** [comment]
It is the URL of the repo

**Comment by RvV1979** [comment]
May I suggest updating the README to reflect this?
